[world]
name = "Glitch Bomb"
description = "Glitch Bomb World"
website = "https://github.com/l10labsxwinwin/glitchbomb"
seed = "GB-1.0.0"

[namespace]
default = "GLITCHBOMB"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
world_address = "0x063d4a0854146d7f6e773b9c38d42156cefc3310524414cc75e61d593792c443"
account_address = "0x059b1a0c489b635d7c7f43594d187362ddd2dcea6c82db4eef2579fd185b3753"
keystore_path = "./keystore_sepolia.json"

[migration]
order_inits = [
    "GLITCHBOMB-VRF",
    "GLITCHBOMB-Token",
    "GLITCHBOMB-Collection",
    "GLITCHBOMB-gb_contract_v2",
]
skip_contracts = ["GLITCHBOMB-VRF"]
disable_multicall = true

[writers]
"GLITCHBOMB" = [
    "GLITCHBOMB-gb_contract_v2",
    "GLITCHBOMB-Collection",
    "GLITCHBOMB-Token",
    "GLITCHBOMB-VRF",
]

[init_call_args]
"GLITCHBOMB-Collection" = []
"GLITCHBOMB-Token" = []
"GLITCHBOMB-VRF" = []
"GLITCHBOMB-gb_contract_v2" = [
    "0x1",                                                                # Collection: Option None
    "0x1",                                                                # Token: Option None
    "0x0",                                                                # VRF: Option Some
    "0x051fea4450da9d6aee758bdeba88b2f665bcbf549d2c61421aa724e9ac0ced8f", # VRF Address
]
