[workspace]
members = ["contracts"]
description = "Glitchbomb World"
cairo-version = "2.12.2"

[workspace.package]
version = "0.0.0"
edition = "2024_07"
cairo-version = "2.12.2"

[workspace.dependencies]
dojo = "1.7.1"
dojo_cairo_test = "1.7.1"
starknet = "2.12.2"
cairo_test = "2.12.2"
openzeppelin = "2.0.0"
alexandria_encoding = "0.6.1"

[workspace.tool.fmt]
sort-module-level-items = true

[tool.scarb]
allow-prebuilt-plugins = ["dojo_cairo_macros"]

[profile.mainnet]
[profile.sepolia]
