[package]
cairo-version = "2.12.2"
name = "glitchbomb"
version = "1.7.1"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[scripts]
k = "katana --dev --dev.no-fee --http.cors_origins '*' --cartridge.paymaster --explorer"
b = "sozo build"
m = "sozo migrate"
bm = "sozo build && sozo migrate --rpc-url http://localhost:5050"
t = "sh -c 'world_address=$(cat manifest_dev.json | jq -r .world.address) && torii -w $world_address --http.cors_origins \"*\" --rpc http://localhost:5050 --http.addr 0.0.0.0 --config torii_dev.toml'"
watch = "find src -name '*.cairo' | entr -c sozo build"
btb = "sozo build --typescript --bindings-output ../sv_client/src/lib && cp manifest_dev.json ../sv_client/src/lib/"

[dependencies]
dojo = "1.7.1"
starknet = "2.12.2"

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[tool.scarb]
allow-prebuilt-plugins = ["dojo_cairo_macros"]

[dev-dependencies]
cairo_test = "2.12.2"
dojo_cairo_test = "1.7.1"
